parameters:
  default_shopify_api_version: '2023-04'
  default_results_per_page: 250
  shopify_arrconfig:
        shop_name: '%env(APP_SHOPIFY_SHOP_NAME)%'
        access_token: '%env(APP_SHOPIFY_ACCESS_TOKEN)%'
        api_version: '%env(default:default_shopify_api_version:APP_SHOPIFY_API_VERSION)%'
        results_per_page: '%env(default:default_results_per_page:APP_SHOPIFY_API_RESULTS_PER_PAGE)%'

services:
  TurboLabIt\ShopifySdk\Connector\ShopifyAdminConnector:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.admin_connector:
    alias: TurboLabIt\ShopifySdk\Connector\ShopifyAdminConnector
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyOrderListRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.order_list_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyOrderListRequest
    public: true

  TurboLabIt\ShopifySdk\DataAdapter\OrderDataAdapter:
      autowire: true
      public: true

  shopifysdk.order_data_adapter:
      alias: TurboLabIt\ShopifySdk\DataAdapter\OrderDataAdapter
      public: true

  TurboLabIt\ShopifySdk\DataAdapter\DataAdapter:
      autowire: true
      public: true

  shopifysdk.data_adapter:
      alias: TurboLabIt\ShopifySdk\DataAdapter\DataAdapter
      public: true

  TurboLabIt\ShopifySdk\Request\ShopifySmartCollectionListRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.smart_collection_list_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifySmartCollectionListRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyMetafieldDefinitionCreateRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.metafield_definition_create_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyMetafieldDefinitionCreateRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyMetafieldDefinitionUpdateRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.metafield_definition_update_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyMetafieldDefinitionUpdateRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifySmartCollectionCreateRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.smart_collection_create_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifySmartCollectionCreateRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifySmartCollectionUpdateRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.smart_collection_update_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifySmartCollectionUpdateRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyPublicationListRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.publication_list_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyPublicationListRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyPublishableRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.publishable_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyPublishableRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyPublishableBulkRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.publishable_bulk_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyPublishableBulkRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyMetaobjectRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.metaobject_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyMetaobjectRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyBulkMutationRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.bulk_mutation_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyBulkMutationRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyProductListRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.product_list_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyProductListRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyProductBulkStatusRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.product_bulk_status_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyProductBulkStatusRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyProductBulkSetRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.product_bulk_set_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyProductBulkSetRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyProductBulkUpdateRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.product_bulk_update_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyProductBulkUpdateRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyInventorySetRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.inventory_set_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyInventorySetRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyProductVariantsBulkUpdateRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.product_variants_bulk_update_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyProductVariantsBulkUpdateRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyProductVariantsBulkCreateRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.product_variants_bulk_create_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyProductVariantsBulkCreateRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyMarketListRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.market_list_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyMarketListRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyCatalogListRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.catalog_list_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyCatalogListRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyMetafieldsSetRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.metafields_set_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyMetafieldsSetRequest
    public: true

  TurboLabIt\ShopifySdk\Request\ShopifyMetafieldsSetBulkRequest:
    autowire: true
    public: true
    arguments:
      $arrConfig: '%shopify_arrconfig%'

  shopifysdk.metafields_set_bulk_request:
    alias: TurboLabIt\ShopifySdk\Request\ShopifyMetafieldsSetBulkRequest
    public: true
